Issue51 no need for dataset parameter model at all
nansencenter/django-geo-spaas pull request #132
Opened 2020-09-25 13:18 UTC by aanersc

closes #51 
@aperrin66 
@akorosov 

Visualization model is removed based on the new viewer. The only thing that remains from this issue#51 is the **DatasetParameter** model which should be checked. as mentioned in #51, there is no need to have the DatasetParameter in the geospaas. All the related content to it is removed and a new migration file is added. The procedure that has been done in this test can be done by django filtering with comma if needed:
https://github.com/nansencenter/django-geo-spaas/blob/704715d53537d4fcda5111d01a9ba278e67e003c/geospaas/catalog/tests.py#L125
We can search through manytomany relationship in django in both direction and that would cause no problem for us to lack DatasetParameter model for this kinds of searching.

Intermediatemodels are only needed when we want to have **extra information** for each of those manytomany relationship which is not the case for us and for django-geospaas parameters and datasets. It is any a simple manytomany relation here for these two:
![image](https://user-images.githubusercontent.com/62345618/94271469-f9600c80-ff41-11ea-91f4-0a71bedf47e3.png)
Here we have only these two. It means it is pointless to have this model!

There is also one line of code in the harvesting repo that should also be removed. That line is also completely useless and no more needed. I will create a separate and issue for that.

2020-09-28 08:07 UTC, aperrin66 commented on geospaas/catalog/migrations/0001_initial.py
> +            field=models.ManyToManyField(to='vocabularies.Parameter'),
Did you modify that manually?

2020-10-02 09:57 UTC, akorosov requested changes
You cannot modify old migrations manually. You should only create new migrations.
See a similar issue here and apply this solution:
https://stackoverflow.com/a/39223849

2020-10-12 09:25 UTC, aanersc commented
@aperrin66 
@akorosov 
No hand-made modification in the migration file! This is done by using the django 'makemigrations' and slightly modifying the autogenerated migration file no.9 in order to successfully migrate as shown in the link of @akorosov  in the above message!

It is ready to merge if you agreed!   :)

2020-10-13 05:46 UTC, aanersc commented
@aperrin66 
@akorosov 
I have tested the tests of both harvesting repo and geospaas repo. It is working. And also I run the harvest.py and it is harvesting without any problem after migrate to the new one. In this migration file, first I remove the intermediary model then create m2m relationship in c519004.

2020-10-13 07:15 UTC, aperrin66 approved these changes
It's ok for me, but existing relationships between parameters and datasets will be lost.
This might be a problem for some users, so:
- the next release needs to be a major version.
- it must be made very clear, in the release notes, what will happen when applying this migration.

2020-10-13 08:34 UTC, akorosov approved these changes

2020-10-14 06:44 UTC, merged